apiVersion: v1
kind: Pod
metadata:
  name: pod
  annotations:
    seccomp-profile.kubernetes.cri-o.io/container: quay.io/crio/seccomp:v1
spec:
  containers:
  - name: container
    image: nginx:1.25.3
  - name: container-unconfined
    image: quay.io/crio/fedora-crio-ci:latest
